### ISSUE TITLE
[EPIC] Restaurant Order Management

### ISSUE THREAD

**Issue by thisissvikas** [Vikas-Open-Source/restaurant-management#1]
As a user I would like to see the menu for the items available at the restaurant. Once I make my choice I would like to place the order pickup the order once it is ready.

As a cook, I would like to see the order that needs to be prepared and also the preferences in queuing if any. 
I would also like the option to mark the order as ready.

As a server, I would like to see the orders that are ready to be handed over to the user and in what order. 
I would also like a way to identify the user that the particular order needs to be handed over to.

We can assume that the payment is going to be handled in cash and at the time of placing the order. The order should be sent to the kitchen only once the payment is completed.

As a manager of the restaurant I should have the view of the all the orders and how much time it has been into the system and what stage is it in. I would also like some kind of mechanism to see the orders that are being delayed and have been in the system for long time.

### Acceptance Criteria
- [ ] All the above personas should be able to perform their designated tasks.
- [ ] The system should be built as an API first system.
- [ ] Each part of the system needs to follow all the design & coding principles applicable.
- [ ] If any breaking changes are introduced in the system, there should be a failure at the build time.
- [ ] The system should be  able to run uniformly on any computer with minimum requirements.
- [ ] The system should be performant and should be vertically scalable to handle high concurrent load.
